"""Constants for the Dreame FP10 integration."""

from __future__ import annotations

from datetime import timedelta

DOMAIN = "dreame_fp10"

CONF_COUNTRY = "country"
CONF_DID = "did"
CONF_HOST = "host"
CONF_MAC = "mac"
CONF_MODEL = "model"
CONF_DEVICE_NAME = "device_name"

DEFAULT_COUNTRY = "eu"
COUNTRY_OPTIONS = ["eu", "us", "cn", "sg", "kr"]

DEFAULT_SCAN_INTERVAL = timedelta(seconds=10)
MIN_SCAN_INTERVAL = 5
MAX_SCAN_INTERVAL = 60
CONF_SCAN_INTERVAL = "scan_interval"

PLATFORMS = ["fan", "sensor", "switch", "number"]

FP10_MODE_AUTO = 0
FP10_MODE_SLEEP = 2
FP10_MODE_MANUAL = 3
FP10_MODE_PET = 4

PRESET_AUTO = "auto"
PRESET_SLEEP = "sleep"
PRESET_MANUAL = "manual"
PRESET_PET = "pet"

PRESET_TO_MODE = {
    PRESET_AUTO: FP10_MODE_AUTO,
    PRESET_SLEEP: FP10_MODE_SLEEP,
    PRESET_MANUAL: FP10_MODE_MANUAL,
    PRESET_PET: FP10_MODE_PET,
}
MODE_TO_PRESET = {value: key for key, value in PRESET_TO_MODE.items()}

FP10_POWER_ON = 1
FP10_POWER_STANDBY = 2

FP10_SPEED_MIN = 1
FP10_SPEED_MAX = 10

MODEL_FP10 = "dreame.airp.u2513"
SUPPORTED_MODELS = {MODEL_FP10}

# Air Purifier is a Matter device type, not a cluster (no 0x005D cluster exists).
MATTER_DEVICE_TYPE_AIR_PURIFIER = "0x002D"
MATTER_CLUSTER_AIR_QUALITY = "0x005B"
MATTER_CLUSTER_FAN_CONTROL = "0x0202"
MATTER_CLUSTER_HEPA_FILTER_MONITORING = "0x0071"
MATTER_CLUSTER_ACTIVATED_CARBON_FILTER_MONITORING = "0x0072"
MATTER_CLUSTER_TEMPERATURE_MEASUREMENT = "0x0402"
MATTER_CLUSTER_RELATIVE_HUMIDITY_MEASUREMENT = "0x0405"
